const events=[['Festival Brisa','18 mai 2025','São Paulo, SP','R$ 24.800','Em alta'],['Conecta Summit','02 jun 2025','Recife, PE','R$ 18.400','Publicado'],['Feira Criativa','21 jun 2025','Curitiba, PR','R$ 12.600','Publicado']]
const accounts=[['Clientes','2.846','+8,2%'],['Fornecedores','384','+12,4%'],['Organizadores','196','+6,8%']]
const fee=(value)=>`R$ ${(Number(value.replace(/\D/g,''))/100).toLocaleString('pt-BR')}`
function Head({title,text}){return <div className="heading"><div><small className="label">Gestão central</small><h2>{title}</h2><p>{text}</p></div><button className="secondary">Ajuda</button></div>}
function EventList(){return <section className="card table"><div className="card-head"><div><h3>Eventos ativos</h3><p>Eventos organizados na plataforma</p></div></div><div className="event-list">{events.map(([name,date,place,value,status])=><div className="event-row" key={name}><span><b className="poster navy"/><strong>{name}</strong></span><span>{date}</span><span>{place}</span><span>{value}</span><em>{status}</em></div>)}</div></section>}
export function AdminScreens({page='home'}){
 if(page==='events')return <><Head title="Eventos ativos" text="Acompanhe os eventos publicados pelos organizadores."/><EventList/></>
 if(page==='income')return <><Head title="Renda da plataforma" text="Seu lucro corresponde a 1% do valor movimentado nos eventos."/><div className="stats"><article className="stat"><span>Receita acumulada<b className="blue">↗</b></span><strong>R$ 18.420</strong><small>+14,6% <i>este mês</i></small></article><article className="stat"><span>Movimentado pelos eventos<b className="blue">↗</b></span><strong>R$ 1,84 mi</strong><small>128 eventos ativos</small></article><article className="stat"><span>Lucro de 1%<b className="blue">◈</b></span><strong>R$ 18.420</strong><small>previsão mensal</small></article></div><section className="card table"><div className="card-head"><div><h3>Receita por evento</h3><p>O cálculo de 1% sobre cada evento organizado</p></div></div><div className="event-list">{events.map(([name,date,,value])=><div className="event-row" key={name}><span><strong>{name}</strong></span><span>{date}</span><span>1%</span><strong>{fee(value)}</strong></div>)}</div></section></>
 if(page==='reports')return <><Head title="Denúncias" text="Acompanhe e resolva situações reportadas pela comunidade."/><section className="card list">{['Descrição enganosa no evento','Fornecedor não entregou o combinado','Comportamento inadequado'].map((item)=><div key={item}><b>!</b><span><strong>{item}</strong><small>Festival Brisa · há 2 horas</small></span><em>Em análise</em></div>)}</section></>
 if(page==='approvals')return <><Head title="Aprovações pendentes" text="Aceite pedidos de cadastro de fornecedores e organizadores."/><section className="card list">{[['Casa Sonora','Fornecedor · CNPJ 12.345.678/0001-90'],['Ana Lima Eventos','Organizador · CPF 123.456.789-00'],['Cenário Vivo','Fornecedor · CNPJ 98.765.432/0001-11']].map(([name,detail])=><div key={name}><span><strong>{name}</strong><small>{detail} · enviado há 3h</small></span><button className="secondary">Ver cadastro</button><button className="approve">Aceitar</button></div>)}</section></>
 return <><Head title="Bom dia, Marina." text="Veja a quantidade de clientes, fornecedores e organizadores cadastrados."/><div className="stats">{accounts.map(([label,value,trend])=><article className="stat" key={label}><span>{label}<b className="blue">↗</b></span><strong>{value}</strong><small>{trend} <i>vs. mês anterior</i></small></article>)}</div><EventList/></>
}
